name: AoC 2015 Solutions
on:
  workflow_dispatch:
    inputs:
      day:
        description: 'Day to execute (leave empty to execute all days)'
        required: false
        default: ''

jobs:
  solve:
    name: Solve Puzzles
    runs-on: ubuntu-latest
    steps:
      - name: Install Haskell
        uses: haskell/actions/setup@v1
      - name: Checkout
        uses: actions/checkout@v1
      - name: Solve
        run: if [ -z "${{ github.event.inputs.day }}" ]; then ./solveAll.sh; else ./solveAll.sh "${{ github.event.inputs.day }}_"; fi
